---
# Source: signalfx-agent/templates/configmap.yaml
apiVersion: v1
data:
  agent.yaml: |
    signalFxAccessToken: ${SFX_ACCESS_TOKEN}

    intervalSeconds: 15

    logging:
      level: info

    globalDimensions:
      kubernetes_cluster: MY-CLUSTER

    sendMachineID: true

    observers:
    - type: k8s-api

    monitors:
    - type: collectd/cpu
    - type: collectd/cpufreq
    - type: collectd/df
      hostFSPath: /hostfs
    - type: collectd/disk
    - type: collectd/interface
    - type: collectd/load
    - type: collectd/memory
    - type: collectd/protocols
    - type: collectd/signalfx-metadata
      procFSPath: /hostfs/proc
      etcPath: /hostfs/etc
      persistencePath: /run
    - type: collectd/uptime
    - type: collectd/vmem

    - type: collectd/processes
      processes:
      - collectd
      - signalfx-agent

    - type: kubelet-stats
      kubeletAPI:
        authType: serviceAccount

    # Collects k8s cluster-level metrics
    - type: kubernetes-cluster

    - type: collectd/docker
      dockerURL: unix:///var/run/docker.sock
      excludedImages:
        - ".*pause-amd64.*"
      dimensions:
        container_image: inspect:Config.Image
        container_id: inspect:Id
        container_spec_name: inspect:Config.Labels['io.kubernetes.container.name']
        # Duplicated for backwards compatibility
        container_name: inspect:Config.Labels['io.kubernetes.container.name']
        kubernetes_pod_name: inspect:Config.Labels['io.kubernetes.pod.name']
        kubernetes_pod_uid: inspect:Config.Labels['io.kubernetes.pod.uid']
        kubernetes_namespace: inspect:Config.Labels['io.kubernetes.pod.namespace']

    - type: collectd/activemq
      discoveryRule: container_image =~ "activemq" && private_port == 1099

    - type: collectd/apache
      discoveryRule: container_image =~ "apache" && private_port == 80

    - type: collectd/cassandra
      discoveryRule: container_image =~ "cassandra" && private_port == 7199

    - type: collectd/consul
      discoveryRule: container_image =~ "consul" && private_port == 8500

    - type: collectd/elasticsearch
      discoveryRule: container_image =~ "elasticsearch" && port == 9200

    - type: collectd/etcd
      discoveryRule: container_image =~ "etcd" && port == 2379
      clusterName: my-cluster

    - type: collectd/haproxy
      discoveryRule: container_image =~ "haproxy" && port == 9000

    - type: collectd/kafka
      discoveryRule: container_image =~ "kafka" && private_port == 9092

    - type: collectd/memcached
      discoveryRule: container_image =~ "memcache" && private_port == 11211

    - type: collectd/mongodb
      discoveryRule: container_image =~ "mongo" && private_port == 27017
      databases:
      - mydatabase

    - type: collectd/mysql
      discoveryRule: container_image =~ "mysql" && private_port == 3306
      databases:
      - name: mydb
      username: admin

    - type: collectd/nginx
      discoveryRule: container_image =~ "nginx" && private_port == 80

    - type: collectd/rabbitmq
      discoveryRule: container_image =~ "rabbitmq" && private_port == 15672

    - type: collectd/redis
      discoveryRule: container_image =~ "redis" && private_port == 6379

    - type: collectd/spark
      discoveryRule: container_image =~ "spark" && private_port == 8080
      clusterType: Standalone
      collectApplicationMetrics: true
      isMaster: true

    - type: collectd/spark
      discoveryRule: container_image =~ "spark" && private_port >= 8081
      clusterType: Standalone
      isMaster: false

    - type: collectd/zookeeper
      discoveryRule: container_image =~ "zookeeper" && private_port == 2181

    collectd:
      readThreads: 5
      writeQueueLimitHigh: 500000
      writeQueueLimitLow: 400000
      timeout: 40
      logLevel: info

    metricsToExclude:
      - metricNames:
        - "container_cpu_user_seconds_total"
        - "container_cpu_system_seconds_total"
        - "container_cpu_usage_seconds_total"
        - "container_cpu_utilization_per_core"
        - "container_fs_reads_total"
        - "container_fs_sector_reads_total"
        - "container_fs_reads_merged_total"
        - "container_fs_read_seconds_total"
        - "container_fs_writes_total"
        - "container_fs_sector_writes_total"
        - "container_fs_writes_merged_total"
        - "container_fs_write_seconds_total"
        - "container_fs_io_current"
        - "container_fs_io_time_seconds_total"
        - "container_fs_io_time_weighted_seconds_total"
        - "container_last_seen"
        - "container_tasks_state"
        - "pod_network_receive_packets_total"
        - "pod_network_receive_packets_dropped_total"
        - "pod_network_transmit_packets_total"
        - "pod_network_transmit_packets_dropped_total"
        - "machine_cpu_frequency_khz"
kind: ConfigMap
metadata:
  name: signalfx-agent
  labels:
    app: signalfx-agent
    
