apiVersion: v1
data:
  merge.yml: |
    dimensions:
       # Replace CLUSTER_NAME with the name of your cluster to be
       # attached as a dimension to all metrics.
       kubernetes_cluster: CLUSTER_NAME
    plugins:
      kubernetes:
        # Set to true to ignore certificate verification checks connecting to kubelet.
        # ignoreTLSVerify: false
kind: ConfigMap
metadata:
  name: signalfx-agent