browse_categories:
- Networking & Content Delivery
data_signature: metric_source:"traefik"
description: Monitoring Traefik reverse proxy / load balancer
display_name: Traefik
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/signalfx-agent-traefik/img/integration_traefik%402x.png
logo_small: /images/repos/signalfx-agent-traefik/img/integration_traefik.png
project_url: https://github.com/signalfx/integrations/tree/master/traefik
